DZ_ansible-2
Otus-DevOps-2022-11/igorborodko_infra pull request #29
Opened 2023-02-12 15:29 UTC by igorborodko

# Выполнено ДЗ № 9 ansible-2

 - [ ] Основное ДЗ
 - [ ] Задание со *

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания
 
--
Создал плейбук site.yml, проверил работу приложения - ОК.

2023-02-16 08:48 UTC, mrgreyves requested changes
Здравствуйте!)
Вам нужно починить тесты
ДЗ возвращаю на доработку

2023-02-16 08:59 UTC, igorborodko commented
Здравствуйте!
Я уже пробовал их чинить в предыдущем ДЗ.
ПРобовал и клонировать заново ветку и  пушить с минимальными изменениями.
Все безуспешно ((

2023-02-16 20:28 UTC, igorborodko commented
Выполнил ДЗ play-travis еще раз - не помогло
Я не понимаю в чем дело...

2023-02-18 12:31 UTC, mrgreyves requested changes
Здравствуйте!
Не очень понимаю, причем тут тесты для дз play-travis
Вы выполняете дз по ansible, сейчас как раз у вас второе дз, то есть ansible-2
Сверяться с тестами нужно именно по нему
Так же у вас не верная структура репозитория, дз возвращаю на доработку

2023-02-20 18:36 UTC, closed without merging